### ISSUE TITLE
it stops on macOS

### ISSUE THREAD

**Issue by okanduzyel** [mcomunita/conditional_wavegan#1]
Hi, I cloned and installed all requirements for the project and then got that error:

```
(base) okanduzyel@Okan-MacBook-Pro conditional_wavegan % python train_cwavegan.py             
Traceback (most recent call last):
  File "/Users/okanduzyel/Downloads/conditional_wavegan/train_cwavegan.py", line 107, in <module>
    train_model(sampling_rate = 16000,
  File "/Users/okanduzyel/Downloads/conditional_wavegan/train_cwavegan.py", line 54, in train_model
    n_classes = utils.get_n_classes(audio_path)
  File "/Users/okanduzyel/Downloads/conditional_wavegan/utils.py", line 9, in get_n_classes
    root, dirs, files = next(os.walk(audio_path))
StopIteration
(base) okanduzyel@Okan-MacBook-Pro conditional_wavegan % 
```

**Comment by mcomunita** [comment]
Hi,

Did you set the path to the audio files `_audio_path = '_data/footsteps_real/'`?
